### ISSUE TITLE
Mark of sergeras/ drop chance

### ISSUE THREAD

**Issue by tropik321** [korakion/Shadowsong#121]
mobs in Nether storm http://www.wowhead.com/npc=18858/wrathbringer does not drops mark of sergeras. the chance of droping it is 58 percent killed over 40+ and none.

**Comment by tropik321** [comment]
In general the drop rate of it from all demons are preaty low.. Same for Fel Armament been farming 2houers+ and got none

**Comment by FearOnCooldown** [comment]
I didn't have any issues with those Marks of Sargeras. You probably grinding in the wrong spot. Like I use to farm.  I'll give you strong place for Marks 41.0 72.6  Peace out dawg.

**Comment by tropik321** [comment]
Yup found that place after i gave up on thoese wrathbringer . rly best spot

**Comment by FearOnCooldown** [comment]
So, please next time consider searching before posting. Close this topic.
