### ISSUE TITLE
Rollback/auction bug?

### ISSUE THREAD

**Issue by Pompros** [korakion/Shadowsong#140]
So i bought an item worth 2378G as soon i bought it the mail appered that it arrived so i was omw to mailbox than i got DC for some reason,and as soon i loged back i got rollback back to the place where i was at AH in stormwind and my gold gone and i havent recieved the item,not even an email apparad again.waited some minutes,than reloged and deleted cachce and nothing.

**Comment by tropik321** [comment]
fixed

**Comment by FearOnCooldown** [comment]
Item has been return to his right owner. 

-Heppi
