### ISSUE TITLE
Quests: The Ogres of Feralas

### ISSUE THREAD

**Issue by Osenis** [korakion/Shadowsong#141]
In this quest (wowhead quest 2975), you have to kill 3 types of Ogres at Gordunni Outpost in Feralas. Gordunni Ogres, Brutes and Ogre Mages. The only Problem is that the Gordunni Ogre Mages con to a skull, mixed in with some level 42+ mobs. Apparently the Ogre Mages are supposed to be levels 41-42, according to wowhead.

**Comment by Arrakoan** [comment]
> This is indeed correct, i can confirm. Some of the ogre mages can even be lvl 211 and some 127.
