### ISSUE TITLE
Quest - "Screecher Spirits" Corpse disappears when attempting to use quest item.

### ISSUE THREAD

**Issue by Hamuminati** [korakion/Shadowsong#163]

**Comment by Lucilla-Korakion** [comment]
Not able to replicate issue - quest worked fine when I tested - see below screenshots:

![screecher1](https://cloud.githubusercontent.com/assets/22416538/18814729/345aab6e-8314-11e6-9188-ea0fa22305e7.PNG)

![screetcher 2](https://cloud.githubusercontent.com/assets/22416538/18814732/454f6860-8314-11e6-9874-07411577df9e.PNG)

Link to original quest: http://www.wowhead.com/quest=3520/screecher-spirits

I was able to find these mobs around the Dock which is the correct area.

Assume fixed so closing this off.

Regards,
Lucilla
