### ISSUE TITLE
Panther Mastery Quest = Bhag'thera not there

### ISSUE THREAD

**Issue by salamort** [korakion/Shadowsong#164]
This mob is suppose to be at loc 49,25 in STV, south of Zul Gurub entrance and north of the Ogre mound, right off the Tree trunk bridge. However Bhag'thera was not there. Waited for 30 mins thinking it might have been killed but still nothing.

GM Arakkoan helped me finish the quest by spawning the mob.
http://www.wowhead.com/npc=728/bhagthera

**Comment by ghost** [comment]
Reviewed:

Hi Salamort,

I can conform that Bhag'thera is there but the cords are slightly different - he is just before you get to the bridge (cords 49,24)

Screenshot provided.

![panther2](https://cloud.githubusercontent.com/assets/2932176/18799962/78024acc-81d2-11e6-958f-c16ff234a2d5.PNG)

He does however have a 30 minute re spawn timer.

Regards,
Hassel

**Comment by Lucilla-Korakion** [comment]
Closing issue as per above.
