### ISSUE TITLE
WArlock quest

### ISSUE THREAD

**Issue by piltybones** [korakion/Shadowsong#176]
I seem to be unable to finish the quest Tome of the Cabal to unlock the felhunter.  I have tried many of times and the chest that contains the tattered manuscript is not lootable!

**Comment by Lucilla-Korakion** [comment]
Hello,

I am not currently able to replicate this problem as was able to loot the Tattered Manuscript just now (see below).

![warlock q](https://cloud.githubusercontent.com/assets/22416538/18816364/25614312-8340-11e6-8363-dcb0b2e65a89.PNG)

Can you try to loot this again please and let me know if you still have an issue?

Thanks,
Lucilla

**Comment by piltybones** [comment]
apparently third time is the charm... this time the chest was lootable... not really sure why the other 2 times I went there it wasn't!

**Comment by Lucilla-Korakion** [comment]
There is a general issue with opening containers sometimes. Usually re-trying or logging off and back on again resolves the problem. I will close this ticket off. 

Regards,
Lucilla
