### ISSUE TITLE
Quest Dry Times

### ISSUE THREAD

**Issue by ghost** [korakion/Shadowsong#18]
Grimbooze Thunderbrew does not offer a keg of Thunderbrew Lager.

**Comment by itsura** [comment]
Same found today. Made a picture i have hops but can't change them with npc for quest item.
![wowscrnshot_090316_153218](https://cloud.githubusercontent.com/assets/543311/18224877/3f7d6500-71ed-11e6-9927-b4cfa3644754.jpg)

**Comment by jordi72** [comment]
Fixed

**Comment by Lucilla-Korakion** [comment]
Tested - This is now fixed on live. Closing report.
