### ISSUE TITLE
paladin quest: The tome of divinity.

### ISSUE THREAD

**Issue by karassavidis** [korakion/Shadowsong#188]
when i use : symbol of life on the npc narm faulk it says: invalid target.

**Comment by Lucilla-Korakion** [comment]
Fixed - item now working as intended (see below):

![forest](https://cloud.githubusercontent.com/assets/22416538/19164415/c8fc471e-8bf7-11e6-9c37-a64d3156c7ba.PNG)

**Comment by Phalyn** [comment]
Seems to be bugged again... I am now getting an "invalid target" message.
