### ISSUE TITLE
Trial of the lake - bug

### ISSUE THREAD

**Issue by NikolajHornum** [korakion/Shadowsong#193]
In the druid quest : Trial of the lake, when i am looting the thing necessary for compleeting the quest, no loot is shown, and i cant try to loot it again. it says "already lootet". i need to complete the quest for aquiring "aquatic form" for my druid. Thanks
Character name: Madarani

**Comment by Lucilla-Korakion** [comment]
Greetings,

Not able to replicate this bug - See below.

![moonglade](https://cloud.githubusercontent.com/assets/22416538/19021983/950cce5e-88c5-11e6-8d54-860b7000f0ec.PNG)

Players can sometimes on the rare occasion see an issue looting containers, however logging off and back on again usually resolves the issue.

Thanks
Lucilla
