### ISSUE TITLE
Trial of the sea lion - bug

### ISSUE THREAD

**Issue by NikolajHornum** [korakion/Shadowsong#194]
When i am trying to loot the "strange lockbox" containing the thing i need for compleeting the quest, it wont loot. then when i try again it says already lootet.

**Comment by Lucilla-Korakion** [comment]
Greetings,

I am not able to replicate this bug - I can loot both items (Darkshore and Westfall), see below:

![darkshore1](https://cloud.githubusercontent.com/assets/22416538/19021940/bf5c919a-88c4-11e6-979a-bb6fcf5c1a38.PNG)

![westfall](https://cloud.githubusercontent.com/assets/22416538/19021942/cc5c7c20-88c4-11e6-804d-2cd701083436.PNG)

If you are still having problems completing the quest please contact a GM in game.

Thanks
Lucilla
