### ISSUE TITLE
Quest - "The Fare of Lar'korwi" Not able to loot "Fresh Threshadon Carcass"

### ISSUE THREAD

**Issue by Hamuminati** [korakion/Shadowsong#195]

**Comment by Lucilla-Korakion** [comment]
Greetings Hamuminati,

I am not able to replicate this problem as I was able to loot the Carcass ok (see below):

![uc1](https://cloud.githubusercontent.com/assets/22416538/19021830/e5667354-88c1-11e6-9732-68445ef0b91e.PNG)

![uc2](https://cloud.githubusercontent.com/assets/22416538/19021832/fcd3cd48-88c1-11e6-90f3-158bf9d42790.PNG)

There is an issue looting containers which happens from time to time but usually a log off / back on again resolves this.

If you are still having an issue completing this quest please contact a GM in game.

Thanks
Lucilla.
