### ISSUE TITLE
10th Mount Achievement

### ISSUE THREAD

**Issue by boldulem** [korakion/Shadowsong#2]
AREA: Achievement
Occurred when I reached 10th level and my inventory bags were full.
What is supposed to happen: Receive an in game mail with a message and the attached mount.
What did happen:  Received in game mail with message of bags are full so instead sent mount.   An in-game mail was sent with no attachments.   Didn't get a mount or a crow feather.
July 18, 2016
Confirmed with another player that they did receive their mount when they reached level 10 but they had an open inventory spot.
Also opened an in game ticket but didn't receive any response, had to leave after an hour.
In game character name: Tieryana

**Comment by wow-mania** [comment]
Normally it should send via mail.
I will check this and fix asap.

**Comment by korakion** [comment]
Hi there,

I sent you the mount via in-game mail.

Thanks for reporting the bug.

Regards,

Janitor
WoW-Mania.com & Korakion.com
The best WotLK and TBC servers

**Comment by boldulem** [comment]
I did receive an in-game mail but only with an attached crow feather with no mount.   Updated original issue to be more clear.

**Comment by boldulem** [comment]
Received both the mount and the crow feathers in game.

Thanks Janitor!

PS, I was unable to reply to you in game to thank you.
