### ISSUE TITLE
Talent bug primal fury, Druid

### ISSUE THREAD

**Issue by NikolajHornum** [korakion/Shadowsong#200]
The talent "primal fury", which is suposed when maxed to give 100% chance of getting an extra combo point when using abilities that grant combo points, dosent work

**Comment by Balsa123** [comment]
I noticed that Primal Fury does not work on live currently. I recorded a Video to show that it will not proc on multiple crits. ([video](https://vid.me/F6KV))

I'm using the vanilla korakion client with it's launcher without any addons on Win 8.1
