### ISSUE TITLE
Hunter spell Aspect of the Pack

### ISSUE THREAD

**Issue by stev0rawr** [korakion/Shadowsong#219]
Hunter spell Aspect of the Pack does not apply to pet.

**Comment by Lucilla-Korakion** [comment]
Sorry I am not able to replicate this issue as this ability is working on pets (See below)

![pet](https://cloud.githubusercontent.com/assets/22416538/19221188/273be362-8e36-11e6-8726-dd14e1439b77.PNG)

If you are still having a problem with it please contact a GM in game or post here and we will get in contact with you.

Regards
Lucilla

**Comment by stev0rawr** [comment]
Hello Lucilla,

 

I logged on today and I am still having the same issue, my pet is Echeyakee. Also GM's haven't been on in almost a week.

 

Thank you for your time,

stev0

Sent: Sunday, October 09, 2016 at 7:36 AM
