### ISSUE TITLE
CORE: Deadly Water

### ISSUE THREAD

**Issue by pallydude** [korakion/Shadowsong#248]
Touching any water right now instantly kills your character.

**Comment by irubenp** [comment]
Janitor fixed this today (march 21)!  I jumped into water and can confirm this is now fixed and water will not kill you.

**Comment by boldulem** [comment]
This issue is back as of 3/30/2017.

**Comment by irubenp** [comment]
April 5th, 2017,  
THE water is LAVA  yet again!!! questing in quel'danas for the shattered sun dailys ... all water is deadly "lava"

**Comment by irubenp** [comment]
April 6th 2017
The water surrounding the isle of quel'danas is STILL LAVA! This issue is still broken and NOT fixed.
