### ISSUE TITLE
Quest: Grim Message (bugged)

### ISSUE THREAD

**Issue by irubenp** [korakion/Shadowsong#254]
in this quest you are sent to Hinterlands to kill winterbark trolls to get 20 heads (starts in booty bay), then combine with a pike and plant it at any witherbark  troll camp in the hinterlands. i was able to collect the heads and combine it with the pike BUT, i'm not able to place the pike down at the camp shown in quest helper and also any other witherbark camp. this make the quest unable to finish.

**Comment by jordi72** [comment]
This report is false, i just did the quest and it works correctly, the only thing, is that you have to go to a specific troll village, to plant the peak.
![2017-04-04 11_15_40-wowscrnshot_040417_111312 - visualizador de fotos de windows](https://cloud.githubusercontent.com/assets/8350580/24650239/e0a18270-1929-11e7-817c-4e7860f93759.png)

![2017-04-04 11_23_19-world of warcraft](https://cloud.githubusercontent.com/assets/8350580/24650257/eee236a4-1929-11e7-8956-28d903743f57.png)
