### ISSUE TITLE
Quest: There Can Be Only One Response (bugged)

### ISSUE THREAD

**Issue by irubenp** [korakion/Shadowsong#268]
http://www.wowhead.com/quest=10867/there-can-be-only-one-response

the quest works until you kill nexus-prince razaan, then he does NOT drop the "collection of souls" item to complete the quest

**Comment by flumby** [comment]
Hello Iru,
Testing a fix for this currently :)

Kind regards

Flumby

**Comment by flumby** [comment]
Trying to locate spell for the creation of the object.  Have a work around ready in case the spell cannot be identified.

**Comment by flumby** [comment]
Fix sent to owner.

**Comment by jemprince** [comment]
Applied to server

**Comment by jemprince** [comment]
Applied to Live server

**Comment by flumby** [comment]
Working.

**Comment by flumby** [comment]
Does not drop.

**Comment by flumby** [comment]
@jemprince did you make that other change i spoke to you about with regards to the one after you applied this?
