### ISSUE TITLE
Quest: Ethereum Secrects (bugged)

### ISSUE THREAD

**Issue by irubenp** [korakion/Shadowsong#269]
http://www.wowhead.com/quest=10971/ethereum-secrets

the issue im seeing is when you do obtain a key to open a ethereum prison... the mobs should be able to target and kill to get a prisoner i.d tag for the quest... the mobs are coming up as friendly so you cant attack them and get an i.d tag quest item.
shown in my screenshot, the nameplate of mob is friendly instead of enemy to target 

![wowscrnshot_042117_212319](https://cloud.githubusercontent.com/assets/26366454/25310464/a93b70a6-2799-11e7-8e9c-ab05eba514fc.jpg)

**Comment by flumby** [comment]
Hello Irubenp,

I have confirmed this issue and have issued a fix to the owner of the server:)

Kind Regards

Flumb

**Comment by flumby** [comment]
Fixed in Live. Closing ticket.
