### ISSUE TITLE
Quest: The Skettis Offensive (bugged)

### ISSUE THREAD

**Issue by irubenp** [korakion/Shadowsong#270]
http://www.wowhead.com/quest=10879/the-skettis-offensive
the bird mobs do appear but are stuck far from the NPC Rilak the Redeemed in which they are supposed to attack him and we are to fight them off... i tried to attack them but they aggro for 1 sec then drop all aggro like we cant hit or target them... the mobs keep appearing in the same place until the Avatar of Terrok appears which is broken also, you cant attack him.
I have two screen shots showing the arrakoa birds and terrok who you cant attack

![wowscrnshot_042417_173502](https://cloud.githubusercontent.com/assets/26366454/25364218/b01ae050-2915-11e7-9e80-df7885c422ae.jpg)
![wowscrnshot_042417_173620](https://cloud.githubusercontent.com/assets/26366454/25364217/b0180466-2915-11e7-94f7-101de3dece45.jpg)

**Comment by flumby** [comment]
Hello, I will apply a fix for this in the test area and get Jem to implement it if it works.

**Comment by flumby** [comment]
Fix has been sent to server owner for application to live.

**Comment by flumby** [comment]
Closing ticket.  Fixed on live.
