### ISSUE TITLE
Azuremist Isle Ocena Water Acts Like Lava

### ISSUE THREAD

**Issue by FatLizardman** [korakion/Shadowsong#274]
The water surrounding Azuremist Isle afew of the rivers have water that acts like lava, making any quest that requires you to swim (IE: Drenai Hunter quest to tame a Barbed Crawler (In ocean waters)) Impossible.
![lava death](https://user-images.githubusercontent.com/36216974/35896604-93a1256a-0b82-11e8-916c-031f2590f8a6.png)

**Comment by jemprince** [comment]
Here's some flags from map.h:
enum ZLiquidStatus
{
    LIQUID_MAP_NO_WATER     = 0x00000000,
    LIQUID_MAP_ABOVE_WATER  = 0x00000001,
    LIQUID_MAP_WATER_WALK   = 0x00000002,
    LIQUID_MAP_IN_WATER     = 0x00000004,
    LIQUID_MAP_UNDER_WATER  = 0x00000008
};

// defined in DBC and left shifted for flag usage
#define MAP_LIQUID_TYPE_NO_WATER    0x00
#define MAP_LIQUID_TYPE_MAGMA       0x01
#define MAP_LIQUID_TYPE_OCEAN       0x02
#define MAP_LIQUID_TYPE_SLIME       0x04
#define MAP_LIQUID_TYPE_WATER       0x08

**Comment by flumby** [comment]
Hello, just like to confirm that this has been fixed.

Kind Regards

Flumby
