### ISSUE TITLE
Hunter pet will not stay tamed after character dies

### ISSUE THREAD

**Issue by FatLizardman** [korakion/Shadowsong#276]
My hunters pets will not stay after the character dies, its as if they run away when said character dies. each time my character dies i have to tame a new pet...

**Comment by flumby** [comment]
Potential fix handed to owner, a change in the pet.cpp file player.cpp file, player.h file, creature.cpp 
, statsystem.cpp, spelleffects.cpp file,  and a couple others.

**Comment by flumby** [comment]
Can confirm in my environment this is now fixed.

You do not lose pet on, dismiss pet, death or log out.

**Comment by FatLizardman** [comment]
Tried taming a pet today.... lost it when trying to mount will test to see if dismissing before mounting prevents this though

**Comment by FatLizardman** [comment]
Lost the pet at dismissal... still not fixed

**Comment by flumby** [comment]
Hello,

IT isn’t yet on the live I am afraid, I have found that it is fixed in the latest dev that I have just waiting for it to be applied to the server.

Korakion Staff

Flumby

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FatLizardman** [comment]
can't even stable the pets they disappear in the process

**Comment by FatLizardman** [comment]
Oh okay

**Comment by flumby** [comment]
Issue has been fixed :)  Pets now save into the database.
