### ISSUE TITLE
Class issue Warlock

### ISSUE THREAD

**Issue by ghost** [korakion/Shadowsong#54]
My Void walker has learned the spells "Consume Shadow" and "Sacrifice" but they aren't on his action bar so I tried to drag them from his spell book to his action bar but the icon doesn't even go when I try to put it in his action bar. But the boarders on his action bar are still glowing like when you have it set to where your pet can use them. Example when you turn your pets taunt on or off. But it's like the spell doesn't exist. I have tried to relearn the spells but it says Spell already known.

**Comment by Jackedcow** [comment]
Issues i have found with my Void would be "Consume Shadow" Rarely works, but still uses the mana. The pathing of the Void is also strange when it comes to Doors and corners. Pretty much every door, small opening, and LoS makes it so the Void won't attack when you command it to. However you just have to slightly walk past said obstacle.

**Comment by Dagger101** [comment]
Having the same problem very annoying when questing.

**Comment by Dagger101** [comment]
Please please fix this, instead of having fun with my lock its a painful leveling grind. Constantly having to use health funnel to heal void so either i drink and eat after nearly every fight or each fight sees me and void half healed, i have never died so much leveling in any class.

**Comment by flumby** [comment]
Warlocks have been fixed apart from the one Consume Shadow spell, this is currently opened in another ticket so i am closing this one.
