### ISSUE TITLE
Into The Scarlet Monastery quest

### ISSUE THREAD

**Issue by Mysterexpo** [korakion/Shadowsong#65]
During this quest High Inquisitor Whitemane does not resurrect Scarlet Commander Morgrain and in doing so you are unable to complete this quest. In fact his body stays put or just follows you around the instance.

**Comment by Jackedcow** [comment]
She will cancel the Rez cast halfway thru to cast smite.

**Comment by Lucilla-Korakion** [comment]
Closing as duplicate of #206
